### ISSUE TITLE
Import Error: No module named 'imageIO'

### ISSUE THREAD

**Issue by Tonthatj** [nyukat/breast_cancer_classifier#8]
Hi everyone I have downloaded the files and when I try to run run.sh, the program breaks at each stage when importing reading_images.py at line 27. ImportError: No module named 'imageio'. I am doing this through the command line. I try to see if it is installed I did pip install imagio and it said requirement already satisfied. I then further try to see if its the path to python by trying to run :python3 import imageio in the same directory, but that command doesn't throw an error.

**Comment by kjgeras** [comment]
Hi Tonthatj,

I think this sounds like an issue

**Comment by jpatrickpark** [comment]
Hi,

Are you working with multiple python environments and could it be possible that you installed imageio in a different environment from the one you are actually using when you execute `run.sh`? Line 27 of reading_images.py is correct, so the problem seems to be arising from your python installation.

**Comment by Tonthatj** [comment]
Hi, there is only one python environment. I agree that your code is correct as when I start an instance of python3 and then copy and past line 27, it does not throw an error. This means Imageio is already installed on the machine. Yet it still throws that error.

**Comment by kjgeras** [comment]
@Tonthatj I'm afraid this is related to your environment and not our code.
